getwd()
setwd("C:/Users/jjgca/Documents/Data-Science/Data Science, Machine Learning, Data Analysis, Data Visualization using Python and R Programming")
read.csv("emp10.csv",sep=",",stringsAsFactors = TRUE)
emp <- read.csv("emp10.csv")
is.data.frame(emp)
typeof(emp)
class(emp)
nrow(emp)
ncol(emp)
dim(emp)
names(emp)
str(emp)
emp[1:6,]
head(emp)
head(emp,n=3)
head(emp,3)
head(emp,-3)
head(emp,4)
tail(emp)
tail(emp,3)
tail(emp,-3)
max(emp$sal)
subset(emp,sal==max(sal))
subset(emp,desig=="data analyst")
subset(emp,sal>65000 & desig=="data analyst")
subset(emp,as.Date(doj) > as.Date("2013-01-01"))
recent_join <- subset(emp,as.Date(doj) > as.Date("2013-01-01"))
print(recent_join)
